version: '3.8'

services:
  techs:
    build: .
    image: techs
    container_name: techs_compose
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - MICRONAUT_ENVIRONMENTS=docker,prod
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres