micronaut:
  application:
    name: tech
  server:
    port: 8080

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

endpoints:
  all:
    path: /management
    sensitive: false
  health:
    jdbc:
      enabled: true
  loggers:
    enabled: true
  stop:
    enabled: true